cmake_minimum_required(VERSION 4.1)
project(20_copy_constructor_and_friends_functions_and_methods_hw)

set(CMAKE_CXX_STANDARD 14)

add_executable(20_copy_constructor_and_friends_functions_and_methods_hw
        main.cpp
        Person.cpp
        Person.h
        Apartment.cpp
        Apartment.h
        ApartmentBuilding.cpp
        ApartmentBuilding.h)
